# Generated by Django 3.2.13 on 2022-12-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_machine_run_data'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runplanitem',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.machine'),
        ),
        migrations.AddField(
            model_name='runplanitem',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.machine'),
        ),
    ]
