# Generated by Django 3.2.13 on 2022-12-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_auto_20221208_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runplanitem',
            options={'verbose_name': 'Run Plan Item'},
        ),
    ]
