# Generated by Django 3.2.13 on 2022-12-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20221216_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='runplanitem',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
