# Generated by Django 3.2.13 on 2022-04-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_unique_id', models.CharField(max_length=32, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_name', models.CharField(max_length=128)),
                ('unique_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=128)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('asset_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.asset', verbose_name='Linked Asset Data')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('manufacture_date', models.DateField()),
                ('flute_profile', models.CharField(choices=[('a', 'A Flute'), ('b', 'B Flute'), ('c', 'C Flute')], max_length=1)),
                ('liner', models.CharField(choices=[('kraft', 'Kraft')], max_length=32)),
                ('layers', models.IntegerField(choices=[(1, 'Single Wall Board'), (2, 'Double Wall Board')])),
                ('delivery_date', models.DateField()),
                ('customer', models.CharField(max_length=32)),
                ('production_status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=32)),
                ('delivery_status', models.CharField(choices=[('storage', 'In Storage'), ('transit', 'In Transit'), ('delivered', 'Delivered')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RunData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('run_hours', models.FloatField()),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('unique_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=64)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.machine')),
            ],
        ),
        migrations.CreateModel(
            name='SubUnit',
            fields=[
                ('unique_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=128)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.machine')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.section')),
            ],
        ),
        migrations.CreateModel(
            name='SubAssembly',
            fields=[
                ('unique_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=128, verbose_name='Sub-Assembly')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.machine')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.section')),
                ('subunit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.subunit')),
            ],
        ),
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('stock_id', models.CharField(max_length=32, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('reorder_quantity', models.IntegerField(default=0)),
                ('last_order_price', models.FloatField(default=0.0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='run_data',
            field=models.ManyToManyField(to='inventory.RunData'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('serial_number', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('order_number', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=32)),
                ('order_date', models.DateField()),
                ('supplier', models.CharField(max_length=32)),
                ('unit_price', models.FloatField()),
                ('min_stock_level', models.IntegerField()),
                ('reorder_quantity', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('unique_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('component_name', models.CharField(max_length=128)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.machine')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.section')),
                ('spares_data', models.ManyToManyField(to='inventory.Spares', verbose_name='linked spares')),
                ('subassembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.subassembly')),
                ('subunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.subunit')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='spares_list',
            field=models.ManyToManyField(to='inventory.Spares'),
        ),
    ]
