# Generated by Django 3.2.13 on 2022-04-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rundata',
            options={'verbose_name': 'Run Schedule'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='spares',
            name='category',
        ),
        migrations.AlterField(
            model_name='machine',
            name='asset_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='subassembly',
            name='unit_name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
    ]
