# Generated by Django 3.2.13 on 2022-12-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('inventory', '0002_auto_20220426_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='spares_list',
        ),
        migrations.AlterField(
            model_name='component',
            name='spares_data',
            field=models.ManyToManyField(to='inventory.Item', verbose_name='linked spares'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='run_data',
            field=models.ManyToManyField(to='planning.RunPlanItem'),
        ),
    ]
