# Generated by Django 3.2.13 on 2022-12-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delete_spares'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RunData',
        ),
    ]
