# Generated by Django 3.2.13 on 2022-12-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('inventory', '0005_delete_rundata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='run_data',
            field=models.ManyToManyField(blank=True, to='planning.RunPlanItem'),
        ),
    ]
