# Generated by Django 3.2.13 on 2022-12-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_machine_run_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='run_data',
        ),
    ]
