# Generated by Django 3.2.13 on 2022-12-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_machine_run_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='order_number',
        ),
    ]
