# Generated by Django 3.2.13 on 2022-12-13 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20221213_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_number', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=128, null=True)),
                ('supplier', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SparesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sparesorder')),
            ],
        ),
    ]
