# Generated by Django 3.2.13 on 2022-04-26 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PreventativeMaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='preventativetask',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='costing',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='type',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='comments',
        ),
        migrations.AddField(
            model_name='workorder',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Costing',
        ),
        migrations.AddField(
            model_name='preventativemaintenanceitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.preventativetask'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.checklist'),
        ),
        migrations.AddField(
            model_name='checklistcomment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.checklist'),
        ),
    ]
