# Generated by Django 3.2.13 on 2022-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20220426_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistcomment',
            options={'verbose_name': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'verbose_name': 'Checklist Item'},
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
