# Generated by Django 3.2.13 on 2022-06-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20220512_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistcomment',
            name='author',
        ),
    ]
