# Generated by Django 3.2.13 on 2022-12-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20221206_1906'),
        ('maintenance', '0004_remove_checklistcomment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventativetask',
            name='required_spares',
            field=models.ManyToManyField(related_name='preventativetask_required_spares', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='spares_used',
            field=models.ManyToManyField(related_name='preventativetask_spares_used', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='sparesrequest',
            name='linked_spares',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='spares_issued',
            field=models.ManyToManyField(related_name='workorder_spares_issued', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='spares_returned',
            field=models.ManyToManyField(related_name='workorder_spares_returned', to='inventory.Item'),
        ),
    ]
