# Generated by Django 3.2.13 on 2022-12-07 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_machine_run_data'),
        ('maintenance', '0005_auto_20221206_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparesrequest',
            old_name='unit',
            new_name='requested_by',
        ),
        migrations.RemoveField(
            model_name='sparesrequest',
            name='linked_spares',
        ),
        migrations.RemoveField(
            model_name='sparesrequest',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sparesrequest',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 7)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SparesRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.sparesrequest')),
            ],
        ),
    ]
