# Generated by Django 3.2.13 on 2022-12-07 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220426_1832'),
        ('inventory', '0006_alter_machine_run_data'),
        ('maintenance', '0006_auto_20221207_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparesrequest',
            name='preventative_task',
        ),
        migrations.AddField(
            model_name='sparesrequest',
            name='requested_for',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='actual_downtime',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(0, 300), '00:05'), (datetime.timedelta(0, 600), '00:10'), (datetime.timedelta(0, 900), '00:15'), (datetime.timedelta(0, 1200), '00:20'), (datetime.timedelta(0, 1500), '00:25'), (datetime.timedelta(0, 1800), '00:30'), (datetime.timedelta(0, 2700), '00:45'), (datetime.timedelta(0, 3600), '01:00'), (datetime.timedelta(0, 4500), '01:15'), (datetime.timedelta(0, 5400), '01:30'), (datetime.timedelta(0, 6300), '01:45'), (datetime.timedelta(0, 7200), '02:00'), (datetime.timedelta(0, 10800), '03:00'), (datetime.timedelta(0, 14400), '04:00'), (datetime.timedelta(0, 18000), '05:00'), (datetime.timedelta(0, 21600), '06:00'), (datetime.timedelta(0, 25200), '07:00'), (datetime.timedelta(0, 28800), '08:00'), (datetime.timedelta(0, 32400), '09:00'), (datetime.timedelta(0, 36000), '10:00'), (datetime.timedelta(0, 39600), '11:00'), (datetime.timedelta(0, 43200), '12:00'), (datetime.timedelta(0, 46800), '13:00'), (datetime.timedelta(0, 50400), '14:00'), (datetime.timedelta(0, 54000), '15:00'), (datetime.timedelta(0, 57600), '16:00'), (datetime.timedelta(0, 61200), '17:00'), (datetime.timedelta(0, 64800), '18:00'), (datetime.timedelta(0, 68400), '19:00'), (datetime.timedelta(0, 72000), '20:00'), (datetime.timedelta(0, 75600), '21:00'), (datetime.timedelta(0, 79200), '22:00')], null=True),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='preventativetask_assignments_made', to='base.Account'),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='assignments_accepted',
            field=models.ManyToManyField(blank=True, related_name='preventativetask_assignments_accepted', to='base.Account'),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.machine'),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='required_spares',
            field=models.ManyToManyField(blank=True, related_name='preventativetask_required_spares', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='spares_used',
            field=models.ManyToManyField(blank=True, related_name='preventativetask_spares_used', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='sparesrequest',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sparesrequest',
            name='requested_by',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='actual_labour_time',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(0, 300), '00:05'), (datetime.timedelta(0, 600), '00:10'), (datetime.timedelta(0, 900), '00:15'), (datetime.timedelta(0, 1200), '00:20'), (datetime.timedelta(0, 1500), '00:25'), (datetime.timedelta(0, 1800), '00:30'), (datetime.timedelta(0, 2700), '00:45'), (datetime.timedelta(0, 3600), '01:00'), (datetime.timedelta(0, 4500), '01:15'), (datetime.timedelta(0, 5400), '01:30'), (datetime.timedelta(0, 6300), '01:45'), (datetime.timedelta(0, 7200), '02:00'), (datetime.timedelta(0, 10800), '03:00'), (datetime.timedelta(0, 14400), '04:00'), (datetime.timedelta(0, 18000), '05:00'), (datetime.timedelta(0, 21600), '06:00'), (datetime.timedelta(0, 25200), '07:00'), (datetime.timedelta(0, 28800), '08:00'), (datetime.timedelta(0, 32400), '09:00'), (datetime.timedelta(0, 36000), '10:00'), (datetime.timedelta(0, 39600), '11:00'), (datetime.timedelta(0, 43200), '12:00'), (datetime.timedelta(0, 46800), '13:00'), (datetime.timedelta(0, 50400), '14:00'), (datetime.timedelta(0, 54000), '15:00'), (datetime.timedelta(0, 57600), '16:00'), (datetime.timedelta(0, 61200), '17:00'), (datetime.timedelta(0, 64800), '18:00'), (datetime.timedelta(0, 68400), '19:00'), (datetime.timedelta(0, 72000), '20:00'), (datetime.timedelta(0, 75600), '21:00'), (datetime.timedelta(0, 79200), '22:00')], null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.account'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='downtime',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(0, 300), '00:05'), (datetime.timedelta(0, 600), '00:10'), (datetime.timedelta(0, 900), '00:15'), (datetime.timedelta(0, 1200), '00:20'), (datetime.timedelta(0, 1500), '00:25'), (datetime.timedelta(0, 1800), '00:30'), (datetime.timedelta(0, 2700), '00:45'), (datetime.timedelta(0, 3600), '01:00'), (datetime.timedelta(0, 4500), '01:15'), (datetime.timedelta(0, 5400), '01:30'), (datetime.timedelta(0, 6300), '01:45'), (datetime.timedelta(0, 7200), '02:00'), (datetime.timedelta(0, 10800), '03:00'), (datetime.timedelta(0, 14400), '04:00'), (datetime.timedelta(0, 18000), '05:00'), (datetime.timedelta(0, 21600), '06:00'), (datetime.timedelta(0, 25200), '07:00'), (datetime.timedelta(0, 28800), '08:00'), (datetime.timedelta(0, 32400), '09:00'), (datetime.timedelta(0, 36000), '10:00'), (datetime.timedelta(0, 39600), '11:00'), (datetime.timedelta(0, 43200), '12:00'), (datetime.timedelta(0, 46800), '13:00'), (datetime.timedelta(0, 50400), '14:00'), (datetime.timedelta(0, 54000), '15:00'), (datetime.timedelta(0, 57600), '16:00'), (datetime.timedelta(0, 61200), '17:00'), (datetime.timedelta(0, 64800), '18:00'), (datetime.timedelta(0, 68400), '19:00'), (datetime.timedelta(0, 72000), '20:00'), (datetime.timedelta(0, 75600), '21:00'), (datetime.timedelta(0, 79200), '22:00')], null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='resolver_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='spares_issued',
            field=models.ManyToManyField(blank=True, related_name='workorder_spares_issued', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='spares_returned',
            field=models.ManyToManyField(blank=True, related_name='workorder_spares_returned', to='inventory.Item'),
        ),
    ]
