# Generated by Django 3.2.13 on 2022-12-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_auto_20221207_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparesrequest',
            name='requested_for',
        ),
        migrations.AddField(
            model_name='sparesrequest',
            name='preventative_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.preventativetask'),
        ),
        migrations.AddField(
            model_name='sparesrequest',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.workorder'),
        ),
    ]
