# Generated by Django 3.2.13 on 2022-12-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_auto_20221208_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparesrequest',
            name='request_type',
            field=models.CharField(choices=[('request', 'Request'), ('request', 'Issue'), ('request', 'Return')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sparesrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=128, null=True),
        ),
    ]
