# Generated by Django 3.2.13 on 2022-12-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_auto_20221208_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventativetask',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('approved', 'Approved'), ('declined', 'Declined')], default='requested', max_length=16),
        ),
        migrations.AlterField(
            model_name='sparesrequest',
            name='request_type',
            field=models.CharField(choices=[('request', 'Request'), ('issue', 'Issue'), ('return', 'Return')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sparesrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=128, null=True),
        ),
    ]
