# Generated by Django 3.2.13 on 2022-12-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_auto_20221213_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventativetask',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventativetask',
            name='void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sparesrequest',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sparesrequest',
            name='void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='void',
            field=models.BooleanField(default=False),
        ),
    ]
