# Generated by Django 3.2.13 on 2022-12-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_account_role'),
        ('maintenance', '0011_auto_20221216_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sparesrequest',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ChecklistHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('no_items_completed', models.IntegerField()),
                ('items_omitted', models.CharField(max_length=1024)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.checklist')),
                ('resolver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.account')),
            ],
        ),
    ]
