# Generated by Django 3.2.13 on 2022-04-25 12:15

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('artisan', 'Artisan'), ('operator', 'Operator')], max_length=128)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_for', models.CharField(choices=[('checklist', 'Checklist'), ('work_order', 'Work Order'), ('preventative_task', 'Preventative Task'), ('reports', 'Reports'), ('spares', 'Spares'), ('inventory', 'Inventory')], max_length=24)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_for', models.CharField(choices=[('checklist', 'Checklist'), ('work_order', 'Work Order'), ('preventative_task', 'Preventative Task')], max_length=24)),
                ('task_number', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_for', models.CharField(choices=[('checklist', 'Checklist'), ('work_order', 'Work Order'), ('preventative_task', 'Preventative Task')], max_length=24)),
                ('content', models.CharField(max_length=1024)),
                ('authored_date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.account')),
            ],
        ),
    ]
