# Generated by Django 3.2.13 on 2022-04-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20220426_1832'),
        ('inventory', '0002_auto_20220426_1832'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
