# Generated by Django 3.2.13 on 2022-12-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220426_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('artisan', 'Artisan'), ('production_planner', 'Production Planner'), ('maintenance_planner', 'Maintenance Planner'), ('inventory_controller', 'Inventory Controller'), ('reports', 'Reports')], max_length=128),
        ),
    ]
